### ISSUE TITLE
Doesn't work when PR mergeable_state = clean

### ISSUE THREAD

**Issue by alexghr** [alexjurkiewicz/pr-comment-github-deployment#1]
Hello,

I've tried to set up this up for my own repos but it fails every time on a simple pull request with the error
```
Error: Deployment failed: PR can't be cleanly merged with base branch.
```

I have tried both a PR that could be `merge --fast-forward` and a PR that needs a merge commit and got the same error.

I've enabled debug logging in my test repo and saw that the pull request payload that Github returned contained this state
```
 "mergeable_state": "clean"
```

As  far as I could tell from the code in `entrypoint.py` this state isn't handled.
https://github.com/alexjurkiewicz/pr-comment-github-deployment/blob/master/entrypoint.py#L156-L176

**Comment by alexjurkiewicz** [comment]
If you were waiting on a license update to fix this, go ahead. I'm not using this action in any workflows at the moment.

**Comment by alexghr** [comment]
Awesome, I'll have a look 👍
